version: '3.8'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"  # TCP порт для ActiveMQ
      - "8161:8161"    # Веб-консоль (доступна по адресу http://localhost:8161)
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048